Sync with macOS workstation

diff --git a/bin/tool-report b/bin/tool-report
--- a/bin/tool-report
+++ b/bin/tool-report
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-set -e
+# NO: set -e
 # DISABLED: set -x
 # Intended to be executed directly by the user.
 ###############################################################################
@@ -42,6 +42,16 @@ checkExecutable bash
 check 'git --version'
 checkExecutable git
 
+# OpenSSL 
+check 'openssl version -a'
+check 'openssl list-cipher-algorithms'
+check 'openssl list-cipher-commands'
+check 'openssl list-message-digest-algorithms'
+check 'openssl list-message-digest-commands'
+check 'openssl list-public-key-algorithms'
+check 'openssl list-standard-commands'
+checkExecutable openssl
+
 # Python shared
 check 'python --version'
 checkExecutable python
@@ -78,22 +88,11 @@ checkExecutable py.test
 check 'aws --version'
 checkExecutable aws
 
-# Git
-check 'git --version'
-checkExecutable git
-
-# OpenSSL 
-check 'openssl version'
-check 'openssl list-cipher-algorithms'
-check 'openssl list-cipher-commands'
-check 'openssl list-message-digest-algorithms'
-check 'openssl list-message-digest-commands'
-check 'openssl list-public-key-algorithms'
-check 'openssl list-standard-commands'
-checkExecutable openssl
+# Python OpenSSL
+check 'python -m OpenSSL.debug'
 
 # Ensure a successful script return
-echo "Tool report succeeded"
+echo "Tool report succeeded, though individual checks may fail"
 exit 0
 
 ###############################################################################
