Sync with another project ; Enhance activation

diff --git a/BriteOnyx/bin/all-capture b/BriteOnyx/bin/all-capture
--- a/BriteOnyx/bin/all-capture
+++ b/BriteOnyx/bin/all-capture
@@ -1,30 +1,33 @@
 #!/usr/bin/env bash
-[[ -n "${BO_Trace}" ]] && echo "TRACE: Executing${BASH_SOURCE}"
+[[ -n "${BO_Debug}" ]] && 1>&2 echo "DEBUG: Executing ${BASH_SOURCE}"
 # NO: set -e
 # Intended to be executed in a BASH shell.
 
 report_status_and_exit() {
     local -ir Status=$?
-    if [[ "${Status}" -eq 0 ]] ; then
-        echo "INFO:  ${0} exiting with status ${Status}"
-    else
-        echo "FATAL: ${0} exiting with status ${Status}"
-    fi
+    [[ "${Status}" -ne 0 ]] && 
+        1>&2 echo "FATAL: ${0} exiting with status ${Status}"
     exit ${Status}
 }
 trap report_status_and_exit EXIT
 ###############################################################################
-# Capture all status
 
-if [[ -z "$BO_Project" ]] ; then
-    echo "FATAL: Environment variable 'BO_Project' is undefined, aborting"
-    exit 1
-fi
+[[ -z "${BO_Project}" ]] && 
+    1>&2 echo "FATAL: This project is NOT ACTIVATED, aborting" && 
+    exit 99
 
-dep-capture
-env-capture
-py-capture
-tool-capture
+main() {
+    # Capture all project configuration status
+
+    dep-capture
+    env-capture
+    py-capture
+    tool-capture
+
+    return 0
+}
+
+main $@
 
 ###############################################################################
 # NOTE: Uncomment these lines for debugging, placed where needed
diff --git a/BriteOnyx/bin/dep-capture b/BriteOnyx/bin/dep-capture
--- a/BriteOnyx/bin/dep-capture
+++ b/BriteOnyx/bin/dep-capture
@@ -1,27 +1,35 @@
 #!/usr/bin/env bash
-[[ -n "${BO_Trace}" ]] && echo "TRACE: Executing${BASH_SOURCE}"
+[[ -n "${BO_Debug}" ]] && 1>&2 echo "DEBUG: Executing ${BASH_SOURCE}"
 # NO: set -e
 # Intended to be executed in a BASH shell.
 
 report_status_and_exit() {
     local -ir Status=$?
-    if [[ "${Status}" -ne 0 ]] ; then
-        echo "FATAL: ${0} exiting with status ${Status}"
-    fi
+    [[ "${Status}" -ne 0 ]] && 
+        1>&2 echo "FATAL: ${0} exiting with status ${Status}"
     exit ${Status}
 }
 trap report_status_and_exit EXIT
 ###############################################################################
-# Capture Python dependency status
 
-[[ -z "${BO_Project}" ]] &&
-    echo "FATAL: 'BO_Project' is undefined, aborting" &&
-    exit 20
+[[ -z "${BO_Project}" ]] && 
+    1>&2 echo "FATAL: This project is NOT ACTIVATED, aborting" && 
+    exit 99
 
 File=$BO_Project/cfg/requirements.txt
 
 echo "INFO:  Capturing Python dependency status to '${File}'"
 >${File} dep-report
+
+main() {
+    # Capture Python dependency status
+
+    # TODO: CONTENT
+
+    return 0
+}
+
+main $@
 
 ###############################################################################
 # NOTE: Uncomment these lines for debugging, placed where needed
diff --git a/BriteOnyx/bin/gen-run b/BriteOnyx/bin/gen-run
--- a/BriteOnyx/bin/gen-run
+++ b/BriteOnyx/bin/gen-run
@@ -1,33 +1,21 @@
 #!/usr/bin/env bash
-[[ -n "${BO_Trace}" ]] && echo "TRACE: Executing${BASH_SOURCE}"
+[[ -n "${BO_Debug}" ]] && 1>&2 echo "DEBUG: Executing ${BASH_SOURCE}"
 # NO: set -e
 # Intended to be executed in a BASH shell.
 
 report_status_and_exit() {
     local -ir Status=$?
-    if [[ "${Status}" -eq 0 ]] ; then
-        echo "INFO:  ${0} exiting with status ${Status}"
-    else
-        echo "FATAL: ${0} exiting with status ${Status}"
-    fi
+    [[ "${Status}" -ne 0 ]] && 
+        1>&2 echo "FATAL: ${0} exiting with status ${Status}"
     exit ${Status}
 }
 trap report_status_and_exit EXIT
 ###############################################################################
 # Generate source
 
-# Require activation
-if [[ -z "$BO_Project" ]] ; then
-    echo "FATAL: Environment variable 'BO_Project' is undefined, aborting"
-    exit 1
-fi
-
-Script=$BO_Project/BriteOnyx/bin/lib/configure-Python.bash
-if [[ -r $Script ]] ; then
-    source $Script
-else
-    echo "WARN: Script file '$Script' is not readable"
-fi
+[[ -z "${BO_Project}" ]] && 
+    1>&2 echo "FATAL: This project is NOT ACTIVATED, aborting" && 
+    exit 99
 
 # Require TMPDIR
 if [[ -z "$TMPDIR" ]] ; then
@@ -48,6 +36,7 @@ cmd+=' -m generate'
 cmd+=" $DirTgt"
 echo $cmd $@
 $cmd $@
+abort_on_fail $? "Source generation failed"
 
 # Merge generated files into project directory
 # TODO: RESEARCH: why Meld does not open a new tab on macOS?
@@ -56,6 +45,16 @@ cmd+=" '$DirTgt' '$BO_Project'"
 cmd+=' >/dev/null 2>&1 &'
 echo "INFO: Use the following command to manually merge the generated source:"
 echo $cmd
+
+main() {
+    # TODO: DESCRIPTION
+
+    # TODO: CONTENT
+
+    return 0
+}
+
+main $@
 
 ###############################################################################
 # NOTE: Uncomment these lines for debugging, placed where needed
diff --git a/BriteOnyx/bin/prj-wipe b/BriteOnyx/bin/prj-wipe
--- a/BriteOnyx/bin/prj-wipe
+++ b/BriteOnyx/bin/prj-wipe
@@ -1,25 +1,21 @@
 #!/usr/bin/env bash
-[[ -n "${BO_Trace}" ]] && echo "TRACE: Executing${BASH_SOURCE}"
+[[ -n "${BO_Debug}" ]] && 1>&2 echo "DEBUG: Executing ${BASH_SOURCE}"
 # NO: set -e
 # Intended to be executed in a BASH shell.
 
 report_status_and_exit() {
     local -ir Status=$?
-    if [[ "${Status}" -eq 0 ]] ; then
-        echo "INFO:  ${0} exiting with status ${Status}"
-    else
-        echo "FATAL: ${0} exiting with status ${Status}"
-    fi
+    [[ "${Status}" -ne 0 ]] && 
+        1>&2 echo "FATAL: ${0} exiting with status ${Status}"
     exit ${Status}
 }
 trap report_status_and_exit EXIT
 ###############################################################################
 # Wipe project directory, which is a deeper clean
 
-if [[ -z "$BO_Project" ]] ; then
-    echo "FATAL: Environment variable 'BO_Project' is undefined, aborting"
-    exit 1
-fi
+[[ -z "${BO_Project}" ]] && 
+    1>&2 echo "FATAL: This project is NOT ACTIVATED, aborting" && 
+    exit 99
 
 if [[ -z "$PVE" ]] ; then
     echo "FATAL: Environment variable 'PVE' is undefined, aborting"
@@ -34,6 +30,16 @@ rm -fr $BO_Project/log
 pve-rm
 
 # TODO: Wipe other caches such as for 'pip'
+
+main() {
+    # TODO: DESCRIPTION
+
+    # TODO: CONTENT
+
+    return 0
+}
+
+main $@
 
 ###############################################################################
 # NOTE: Uncomment these lines for debugging, placed where needed
diff --git a/BriteOnyx/bin/py-2to3 b/BriteOnyx/bin/py-2to3
--- a/BriteOnyx/bin/py-2to3
+++ b/BriteOnyx/bin/py-2to3
@@ -1,25 +1,21 @@
 #!/usr/bin/env bash
-[[ -n "${BO_Trace}" ]] && echo "TRACE: Executing${BASH_SOURCE}"
+[[ -n "${BO_Debug}" ]] && 1>&2 echo "DEBUG: Executing ${BASH_SOURCE}"
 # NO: set -e
 # Intended to be executed in a BASH shell.
 
 report_status_and_exit() {
     local -ir Status=$?
-    if [[ "${Status}" -eq 0 ]] ; then
-        echo "INFO:  ${0} exiting with status ${Status}"
-    else
-        echo "FATAL: ${0} exiting with status ${Status}"
-    fi
+    [[ "${Status}" -ne 0 ]] && 
+        1>&2 echo "FATAL: ${0} exiting with status ${Status}"
     exit ${Status}
 }
 trap report_status_and_exit EXIT
 ###############################################################################
 # Convert all Python source from Python2 to Python3
 
-if [[ -z "$BO_Project" ]] ; then
-    echo "FATAL: Environment variable 'BO_Project' is undefined, aborting"
-    exit 1
-fi
+[[ -z "${BO_Project}" ]] && 
+    1>&2 echo "FATAL: This project is NOT ACTIVATED, aborting" && 
+    exit 99
 
 # NOTE: Apparently, it is not possible to run Python3 code exclusively with the
 # .py3 file extension, so do not add a '3' suffix to the source files.
@@ -97,6 +93,16 @@ convert $BO_Project/src/app
 convert $BO_Project/src/gen
 convert $BO_Project/src/lib/mine
 convert $BO_Project/src/lib/third_party
+
+main() {
+    # TODO: DESCRIPTION
+
+    # TODO: CONTENT
+
+    return 0
+}
+
+main $@
 
 ###############################################################################
 # NOTE: Uncomment these lines for debugging, placed where needed
diff --git a/BriteOnyx/bin/sig-make b/BriteOnyx/bin/sig-make
--- a/BriteOnyx/bin/sig-make
+++ b/BriteOnyx/bin/sig-make
@@ -1,23 +1,21 @@
 #!/usr/bin/env bash
-[[ -n "${BO_Trace}" ]] && echo "TRACE: Executing${BASH_SOURCE}"
+[[ -n "${BO_Debug}" ]] && 1>&2 echo "DEBUG: Executing ${BASH_SOURCE}"
 # NO: set -e
 # Intended to be executed in a BASH shell.
 
 report_status_and_exit() {
     local -ir Status=$?
-    if [[ "${Status}" -eq 0 ]] ; then
-        echo "INFO:  ${0} exiting with status ${Status}"
-    else
-        echo "FATAL: ${0} exiting with status ${Status}"
-    fi
+    [[ "${Status}" -ne 0 ]] && 
+        1>&2 echo "FATAL: ${0} exiting with status ${Status}"
     exit ${Status}
 }
 trap report_status_and_exit EXIT
 ###############################################################################
 # Make a signature file for directory $1
 
-dir=$1
-[[ -z "${dir}" ]] && dir=${PWD}
+[[ -z "${BO_Project}" ]] && 
+    1>&2 echo "FATAL: This project is NOT ACTIVATED, aborting" && 
+    exit 99
 
 file=shasum-256.sig
 
@@ -25,6 +23,16 @@ echo "INFO:  Making signature file ${dir}/${file}"
 cd ${dir}
 shasum -p -a 256 * 2>/dev/null | grep -v ${file} >${file}
 cat ${file}
+
+main() {
+    # TODO: DESCRIPTION
+
+    # TODO: CONTENT
+
+    return 0
+}
+
+main $@
 
 ###############################################################################
 # NOTE: Uncomment these lines for debugging, placed where needed
diff --git a/BriteOnyx/bin/test-run b/BriteOnyx/bin/test-run
--- a/BriteOnyx/bin/test-run
+++ b/BriteOnyx/bin/test-run
@@ -1,30 +1,20 @@
 #!/usr/bin/env bash
-[[ -n "${BO_Trace}" ]] && echo "TRACE: Executing${BASH_SOURCE}"
+[[ -n "${BO_Debug}" ]] && 1>&2 echo "DEBUG: Executing ${BASH_SOURCE}"
 # NO: set -e
 # Intended to be executed in a BASH shell.
 
 report_status_and_exit() {
     local -ir Status=$?
-    if [[ "${Status}" -eq 0 ]] ; then
-        echo "INFO:  ${0} exiting with status ${Status}"
-    else
-        echo "FATAL: ${0} exiting with status ${Status}"
-    fi
+    [[ "${Status}" -ne 0 ]] && 
+        1>&2 echo "FATAL: ${0} exiting with status ${Status}"
     exit ${Status}
 }
 trap report_status_and_exit EXIT
 ###############################################################################
 
-[[ -z "${BO_Project}" ]] &&
-    echo "FATAL: 'BO_Project' is undefined, aborting" &&
-    exit 20
-
-Script=${BO_Project}/BriteOnyx/bin/lib/configure-Python.bash
-if [[ -r ${Script} ]] ; then
-    source ${Script}
-else
-    echo "WARN: Script file '${Script}' is not readable"
-fi
+[[ -z "${BO_Project}" ]] && 
+    1>&2 echo "FATAL: This project is NOT ACTIVATED, aborting" && 
+    exit 99
 
 run_pytest() {
     # Run pytest on test suite known as $1 in directory $2
@@ -48,11 +38,13 @@ run_pytest() {
 main() {
     # Run Python test suites
     # TODO: Separate coverage generation into consolidated step
+
     run_pytest mine ${BO_Project}/src/lib/mine
     run_pytest gen  ${BO_Project}/src/gen
     run_pytest app  ${BO_Project}/src/app
     coverage report --rcfile=${BO_Project}/cfg/.coveragerc
     Status=$? ; [[ ${Status} -ne 0 ]] && exit ${Status}
+
     return 0
 }
 
diff --git a/bin/app-run b/bin/app-run
--- a/bin/app-run
+++ b/bin/app-run
@@ -1,15 +1,12 @@
 #!/usr/bin/env bash
-[[ -n "${BO_Trace}" ]] && echo "TRACE: Executing${BASH_SOURCE}"
+[[ -n "${BO_Debug}" ]] && 1>&2 echo "DEBUG: Executing ${BASH_SOURCE}"
 # NO: set -e
 # Intended to be executed in a BASH shell.
 
 report_status_and_exit() {
     local -ir Status=$?
-    if [[ "${Status}" -eq 0 ]] ; then
-        echo "INFO:  ${0} exiting with status ${Status}"
-    else
-        echo "FATAL: ${0} exiting with status ${Status}"
-    fi
+    [[ "${Status}" -ne 0 ]] && 
+        1>&2 echo "FATAL: ${0} exiting with status ${Status}"
     exit ${Status}
 }
 trap report_status_and_exit EXIT
@@ -21,18 +18,9 @@ trap report_status_and_exit EXIT
 # will happen as needed.  If this script is unable to finish, then it should
 # abort after giving the user feedback about how they might proceed further.
 
-# Require activation
-if [[ -z "$BO_Project" ]] ; then
-    echo "FATAL: Environment variable 'BO_Project' is undefined, aborting"
-    exit 1
-fi
-
-Script=$BO_Project/BriteOnyx/bin/lib/configure-Python.bash
-if [[ -r $Script ]] ; then
-    source $Script
-else
-    echo "WARN: Script file '$Script' is not readable"
-fi
+[[ -z "${BO_Project}" ]] && 
+    1>&2 echo "FATAL: This project is NOT ACTIVATED, aborting" && 
+    exit 99
 
 cd $BO_Project/src/app
 
@@ -42,6 +30,16 @@ cmd='python3'
 cmd+=' -m MODULE'
 echo $cmd $@
 $cmd $@
+
+main() {
+    # TODO: DESCRIPTION
+
+    # TODO: CONTENT
+
+    return 0
+}
+
+main $@
 
 ###############################################################################
 # NOTE: Uncomment these lines for debugging, placed where needed
diff --git a/bin/source-may-be-left-out b/bin/source-may-be-left-out
--- a/bin/source-may-be-left-out
+++ b/bin/source-may-be-left-out
@@ -1,19 +1,20 @@
 #!/usr/bin/env bash
-[[ -n "${BO_Trace}" ]] && echo "TRACE: Executing${BASH_SOURCE}"
+[[ -n "${BO_Debug}" ]] && 1>&2 echo "DEBUG: Executing ${BASH_SOURCE}"
 # NO: set -e
 # Intended to be executed in a BASH shell.
 
 report_status_and_exit() {
     local -ir Status=$?
-    if [[ "${Status}" -eq 0 ]] ; then
-        echo "INFO:  ${0} exiting with status ${Status}"
-    else
-        echo "FATAL: ${0} exiting with status ${Status}"
-    fi
+    [[ "${Status}" -ne 0 ]] && 
+        1>&2 echo "FATAL: ${0} exiting with status ${Status}"
     exit ${Status}
 }
 trap report_status_and_exit EXIT
 ###############################################################################
+
+[[ -z "${BO_Project}" ]] && 
+    1>&2 echo "FATAL: This project is NOT ACTIVATED, aborting" && 
+    exit 99
 
 main() {
     # List files that are ignored by source control but MAY be wrongly left out
@@ -32,6 +33,8 @@ main() {
         grep -v htmlcov\/ |
         grep -v log\/ |
         grep -v pytest\.log
+
+    return 0
 }
 
 main $@
