Implement pytest coverage

diff --git a/BriteOnyx/bin/dep-capture b/BriteOnyx/bin/dep-capture
--- a/BriteOnyx/bin/dep-capture
+++ b/BriteOnyx/bin/dep-capture
@@ -16,15 +16,14 @@ trap report_status_and_exit EXIT
 ###############################################################################
 # Capture Python dependency status
 
-if [[ -z "$BO_Project" ]] ; then
-    echo "FATAL: Environment variable 'BO_Project' is undefined, aborting"
-    exit 1
-fi
+[[ -z "${BO_Project}" ]] &&
+    echo "FATAL: 'BO_Project' is undefined, aborting" &&
+    exit 20
 
 File=$BO_Project/cfg/requirements.txt
 
-echo "INFO: Capturing Python dependency status to '$File'"
-dep-report > $File
+echo "INFO:  Capturing Python dependency status to '${File}'"
+>${File} 2>&1 dep-report
 
 ###############################################################################
 # NOTE: Uncomment these lines for debugging, placed where needed
diff --git a/BriteOnyx/bin/env-capture b/BriteOnyx/bin/env-capture
--- a/BriteOnyx/bin/env-capture
+++ b/BriteOnyx/bin/env-capture
@@ -16,18 +16,17 @@ trap report_status_and_exit EXIT
 ###############################################################################
 # Capture BASH environment status
 
-if [[ -z "$BO_Project" ]] ; then
-    echo "FATAL: Environment variable 'BO_Project' is undefined, aborting"
-    exit 1
-fi
+[[ -z "${BO_Project}" ]] &&
+    echo "FATAL: 'BO_Project' is undefined, aborting" &&
+    exit 20
 
-File=$BO_Project/out/env.out
+File=${BO_Project}/out/env.out
 
-echo "INFO: Capturing BASH environment status to '$File'"
-env-report > $File
+echo "INFO:  Capturing BASH environment status to '${File}'"
+>${File} 2>&1 env-report
 
 # Capture activation output
-cp $BO_Project/*.env $BO_Project/out
+cp ${BO_Project}/*.env ${BO_Project}/out
 
 ###############################################################################
 # NOTE: Uncomment these lines for debugging, placed where needed
diff --git a/BriteOnyx/bin/py-capture b/BriteOnyx/bin/py-capture
--- a/BriteOnyx/bin/py-capture
+++ b/BriteOnyx/bin/py-capture
@@ -16,15 +16,14 @@ trap report_status_and_exit EXIT
 ###############################################################################
 # Capture Python status
 
-if [[ -z "$BO_Project" ]] ; then
-    echo "FATAL: Environment variable 'BO_Project' is undefined, aborting"
-    exit 1
-fi
+[[ -z "${BO_Project}" ]] &&
+    echo "FATAL: 'BO_Project' is undefined, aborting" &&
+    exit 20
 
-File=$BO_Project/out/python.out
+File=${BO_Project}/out/python.out
 
-echo "INFO: Capturing Python status to '$File'"
-py-report > $File
+echo "INFO:  Capturing Python status to '${File}'"
+>${File} py-report
 
 ###############################################################################
 # NOTE: Uncomment these lines for debugging, placed where needed
diff --git a/BriteOnyx/bin/py-report b/BriteOnyx/bin/py-report
--- a/BriteOnyx/bin/py-report
+++ b/BriteOnyx/bin/py-report
@@ -16,24 +16,25 @@ trap report_status_and_exit EXIT
 ###############################################################################
 # Report Python code status
 
-if [[ -z "$BO_Project" ]] ; then
-    echo "FATAL: Environment variable 'BO_Project' is undefined, aborting"
-    exit 1
-fi
+[[ -z "${BO_Project}" ]] &&
+    echo "FATAL: 'BO_Project' is undefined, aborting" &&
+    exit 20
 
 clear
 
-python3 -m tabnanny -v $BO_Project/BriteOnyx/bin >$BO_Project/out/tabnanny.out
-python3 -m tabnanny -v $BO_Project/bin          >>$BO_Project/out/tabnanny.out
-python3 -m tabnanny -v $BO_Project/src/app      >>$BO_Project/out/tabnanny.out
-python3 -m tabnanny -v $BO_Project/src/gen      >>$BO_Project/out/tabnanny.out
-python3 -m tabnanny -v $BO_Project/src/lib      >>$BO_Project/out/tabnanny.out
-
-cat $BO_Project/out/tabnanny.out \
+Out=${BO_Project}/out/tabnanny.out
+ >${Out} 2>&1 python3 -m tabnanny -v ${BO_Project}/BriteOnyx/bin
+>>${Out} 2>&1 python3 -m tabnanny -v ${BO_Project}/bin
+>>${Out} 2>&1 python3 -m tabnanny -v ${BO_Project}/src/app
+>>${Out} 2>&1 python3 -m tabnanny -v ${BO_Project}/src/gen
+>>${Out} 2>&1 python3 -m tabnanny -v ${BO_Project}/src/lib
+cat ${Out} \
     | grep -v 'listing directory' \
     | grep -v 'Clean bill of health.'
-
 echo 'INFO: No output means all Python code passes all TabNanny checks'
+
+Out=${BO_Project}/out/py-reformat.out
+>${Out} 2>&1 py-reformat
 
 ###############################################################################
 # NOTE: Uncomment these lines for debugging, placed where needed
diff --git a/BriteOnyx/bin/tool-capture b/BriteOnyx/bin/tool-capture
--- a/BriteOnyx/bin/tool-capture
+++ b/BriteOnyx/bin/tool-capture
@@ -16,15 +16,14 @@ trap report_status_and_exit EXIT
 ###############################################################################
 # Capture tool status
 
-if [[ -z "$BO_Project" ]] ; then
-    echo "FATAL: Environment variable 'BO_Project' is undefined, aborting"
-    exit 1
-fi
+[[ -z "${BO_Project}" ]] &&
+    echo "FATAL: 'BO_Project' is undefined, aborting" &&
+    exit 20
 
 File=$BO_Project/out/tool.out
 
-echo "INFO: Capturing tool status to '$File'"
-tool-report 2>&1 >$File
+echo "INFO:  Capturing tool status to '${File}'"
+>${File} 2>&1 tool-report
 
 ###############################################################################
 # NOTE: Uncomment these lines for debugging, placed where needed
