Enhance scripts to handle pathnames with spaces

diff --git a/BriteOnyx/bin/env-check b/BriteOnyx/bin/env-check
--- a/BriteOnyx/bin/env-check
+++ b/BriteOnyx/bin/env-check
@@ -8,20 +8,20 @@ trap warn_on_error EXIT
     1>&2 echo "ERROR: Aborting, this project is NOT ACTIVATED" &&
     exit 99
 
-File=$BO_Project/out/env.out
-
-if [[ ! -r "$File" ]] ; then
-    log_error "Bash environment status file '$File' is unreadable, aborting"
-    exit 1
-fi
-
-log_debug "Checking Bash environment status against '$File'"
-env-report | diff - $File
-
 main() {
     # Check Bash environment status
+    # TODO: FIX: Why does this break?
+    require_arguments $# 0
 
-    # TODO: CONTENT
+    local -r File=${BO_Project}/out/env.out
+
+    if [[ ! -r "${File}" ]] ; then
+        log_error "Bash environment status file '${File}' is unreadable, aborting"
+        exit 1
+    fi
+
+    log_debug "Checking Bash environment status against '${File}'"
+    env-report | diff - "${File}"
 
     return 0
 }
diff --git a/BriteOnyx/bin/py-check b/BriteOnyx/bin/py-check
--- a/BriteOnyx/bin/py-check
+++ b/BriteOnyx/bin/py-check
@@ -8,20 +8,19 @@ trap warn_on_error EXIT
     1>&2 echo "ERROR: Aborting, this project is NOT ACTIVATED" &&
     exit 99
 
-File=$BO_Project/out/Python.out
-
-if [[ ! -r "$File" ]] ; then
-    log_error "Python status file '$File' is unreadable, aborting"
-    exit 1
-fi
-
-log_debug "Checking Python status against '$File'"
-py-report | diff - $File
-
 main() {
     # Check Python status
+    require_arguments $# 0
 
-    # TODO: CONTENT
+    local -r File=${BO_Project}/out/Python.out
+
+    if [[ ! -r "${File}" ]] ; then
+        log_error "Python status file '${File}' is unreadable, aborting"
+        exit 1
+    fi
+
+    log_debug "Checking Python status against '${File}'"
+    py-report | diff - "${File}"
 
     return 0
 }
diff --git a/BriteOnyx/bin/tool-check b/BriteOnyx/bin/tool-check
--- a/BriteOnyx/bin/tool-check
+++ b/BriteOnyx/bin/tool-check
@@ -8,20 +8,19 @@ trap warn_on_error EXIT
     1>&2 echo "ERROR: Aborting, this project is NOT ACTIVATED" &&
     exit 99
 
-File=$BO_Project/out/tool.out
-
-if [[ ! -r "$File" ]] ; then
-    log_error "Tool status file '$File' is unreadable, aborting"
-    exit 1
-fi
-
-log_debug "Checking tool status against '$File'"
-tool-report | diff - $File
-
 main() {
     # Check tool status
+    require_arguments $# 0
 
-    # TODO: CONTENT
+    local -r File=${BO_Project}/out/tool.out
+
+    if [[ ! -r "${File}" ]] ; then
+        log_error "Tool status file '${File}' is unreadable, aborting"
+        exit 1
+    fi
+
+    log_debug "Checking tool status against '${File}'"
+    tool-report | diff - "${File}"
 
     return 0
 }
