Sync with another project

diff --git a/BriteOnyx/bin/env-capture b/BriteOnyx/bin/env-capture
--- a/BriteOnyx/bin/env-capture
+++ b/BriteOnyx/bin/env-capture
@@ -1,32 +1,24 @@
 #!/usr/bin/env bash
-[[ -n "${BO_Debug}" ]] && 1>&2 echo "DEBUG: Executing ${BASH_SOURCE}"
+[[ -n "${BO_Debug}" ]] && 1>&2 echo "Executing ${BASH_SOURCE}"
 # NO: set -e
 # Intended to be executed in a BASH shell.
-
-report_status_and_exit() {
-    local -ir Status=$?
-    [[ "${Status}" -ne 0 ]] && 
-        1>&2 echo "FATAL: ${0} exiting with status ${Status}"
-    exit ${Status}
-}
-trap report_status_and_exit EXIT
+trap warn_on_error EXIT
 ###############################################################################
-# Capture BASH environment status
-
-[[ -z "${BO_Project}" ]] && 
-    1>&2 echo "FATAL: This project is NOT ACTIVATED, aborting" && 
+[[ -z "${BO_Project}" ]] &&
+    log_error "Aborting, this project is NOT ACTIVATED" &&
     exit 99
 
 File=${BO_Project}/out/env.out
 
-echo "INFO:  Capturing BASH environment status to '${File}'"
->${File} 2>&1 env-report
+log_debug "Capturing BASH environment status to '${File}'"
+&>${File} \
+    env-report
 
 # Capture activation output
 cp ${BO_Project}/*.env ${BO_Project}/out
 
 main() {
-    # TODO: DESCRIPTION
+    # Capture BASH environment status
 
     # TODO: CONTENT
 
@@ -37,11 +29,9 @@ main $@
 
 ###############################################################################
 # NOTE: Uncomment these lines for debugging, placed where needed
-# set -o verbose
-# set -o xtrace
+# export PS4='$ ' ; set -o verbose ; set -o xtrace
 # Code to debug...
-# set +o verbose
-# set +o xtrace
+# set +o verbose ; set +o xtrace
 : << 'DisabledContent'
 DisabledContent
 
diff --git a/BriteOnyx/bin/gen-run b/BriteOnyx/bin/gen-run
--- a/BriteOnyx/bin/gen-run
+++ b/BriteOnyx/bin/gen-run
@@ -1,55 +1,42 @@
 #!/usr/bin/env bash
-[[ -n "${BO_Debug}" ]] && 1>&2 echo "DEBUG: Executing ${BASH_SOURCE}"
+[[ -n "${BO_Debug}" ]] && 1>&2 echo "Executing ${BASH_SOURCE}"
 # NO: set -e
 # Intended to be executed in a BASH shell.
-
-report_status_and_exit() {
-    local -ir Status=$?
-    [[ "${Status}" -ne 0 ]] && 
-        1>&2 echo "FATAL: ${0} exiting with status ${Status}"
-    exit ${Status}
-}
-trap report_status_and_exit EXIT
+trap warn_on_error EXIT
 ###############################################################################
-# Generate source
-
-[[ -z "${BO_Project}" ]] && 
-    1>&2 echo "FATAL: This project is NOT ACTIVATED, aborting" && 
+[[ -z "${BO_Project}" ]] &&
+    log_error "Aborting, this project is NOT ACTIVATED" &&
     exit 99
 
-# Require TMPDIR
-if [[ -z "$TMPDIR" ]] ; then
-    echo "FATAL: Environment variable 'TMPDIR' is undefined, aborting"
-    exit 1
-fi
-
-# Recreate target directory (handled within Python)
-DirTgt=$TMPDIR/tgt
-
-echo "INFO: Generating content into directory '$DirTgt'"
-cd $BO_Project/src/gen
-
-# Execute Python
-cmd='python3'
-# cmd+=' -bb'
-cmd+=' -m generate'
-cmd+=" $DirTgt"
-echo $cmd $@
-$cmd $@
-abort_on_fail $? "Source generation failed"
-
-# Merge generated files into project directory
-# TODO: RESEARCH: why Meld does not open a new tab on macOS?
-cmd='meld --newtab'
-cmd+=" '$DirTgt' '$BO_Project'"
-cmd+=' >/dev/null 2>&1 &'
-echo "INFO: Use the following command to manually merge the generated source:"
-echo $cmd
-
 main() {
-    # TODO: DESCRIPTION
+    # Generate source
+    local Cmd
+    
+    require_directory_in_variable BO_Project
+    require_directory_in_variable TMPDIR
 
-    # TODO: CONTENT
+    # Recreate target directory (handled within Python)
+    # TODO: Unify this reference with the other
+    local -r DirTgt=$TMPDIR/tgt
+
+    log_debug "Generating source into directory '$DirTgt'"
+    cd ${BO_Project}/src/gen ; abort_on_fail $?
+    Cmd='python3'
+    # Cmd+=' -bb'
+    Cmd+=' -m generate'
+    Cmd+=" ${DirTgt}"
+    ${Cmd} $@
+    abort_on_fail $? "Source generation failed"
+
+    log_debug "Use the following command to manually merge the generated source:"
+    # TODO: RESEARCH: why Meld does not open a new tab on macOS?
+    Cmd='&>/dev/null'
+    Cmd+=' meld'
+    Cmd+=' ${BO_Project}'
+    # TODO: Unify this reference with the other
+    Cmd+=' $TMPDIR/tgt'
+    Cmd+=' &'
+    log_info "${Cmd}"
 
     return 0
 }
@@ -58,11 +45,9 @@ main $@
 
 ###############################################################################
 # NOTE: Uncomment these lines for debugging, placed where needed
-# set -o verbose
-# set -o xtrace
+# export PS4='$ ' ; set -o verbose ; set -o xtrace
 # Code to debug...
-# set +o verbose
-# set +o xtrace
+# set +o verbose ; set +o xtrace
 : << 'DisabledContent'
 DisabledContent
 
diff --git a/BriteOnyx/bin/prj-clean b/BriteOnyx/bin/prj-clean
--- a/BriteOnyx/bin/prj-clean
+++ b/BriteOnyx/bin/prj-clean
@@ -1,24 +1,15 @@
 #!/usr/bin/env bash
-[[ -n "${BO_Debug}" ]] && 1>&2 echo "DEBUG: Executing ${BASH_SOURCE}"
+[[ -n "${BO_Debug}" ]] && 1>&2 echo "Executing ${BASH_SOURCE}"
 # NO: set -e
 # Intended to be executed in a BASH shell.
-
-report_status_and_exit() {
-    local -ir Status=$?
-    [[ "${Status}" -ne 0 ]] && 
-        1>&2 echo "FATAL: ${0} exiting with status ${Status}"
-    exit ${Status}
-}
-trap report_status_and_exit EXIT
+trap warn_on_error EXIT
 ###############################################################################
-# Clean project directory
-
-[[ -z "${BO_Project}" ]] && 
-    1>&2 echo "FATAL: This project is NOT ACTIVATED, aborting" && 
+[[ -z "${BO_Project}" ]] &&
+    log_error "Aborting, this project is NOT ACTIVATED" &&
     exit 99
 
 if [[ -z "$PVE" ]] ; then
-    echo "FATAL: Environment variable 'PVE' is undefined, aborting"
+    log_error "Environment variable 'PVE' is undefined, aborting"
     exit 1
 fi
 
@@ -35,34 +26,34 @@ findAnd() {
 	-$1
 }
 
-echo "INFO: Found these files..."
+log_debug "Found these files..."
 findAnd print $BO_Project '*.bak'
 findAnd print $BO_Project '*.log'
 findAnd print $BO_Project '*.pyc'
 findAnd print $BO_Project '__pycache__'
 
-echo "INFO: Deleting files..."
+log_debug "Deleting files..."
 findAnd delete $BO_Project '*.bak'
 findAnd delete $BO_Project '*.pyc'
 findAnd delete $BO_Project '__pycache__'
 
 _file=$BO_Project/src/app/pytest.log
-[[ -f "$_file" ]] && echo "INFO: Deleting file '$_file'" && rm $_file
+[[ -f "$_file" ]] && log_debug "Deleting file '$_file'" && rm $_file
 _file=$BO_Project/src/gen/pytest.log
-[[ -f "$_file" ]] && echo "INFO: Deleting file '$_file'" && rm $_file
+[[ -f "$_file" ]] && log_debug "Deleting file '$_file'" && rm $_file
 _file=$BO_Project/src/lib/mine/pytest.log
-[[ -f "$_file" ]] && echo "INFO: Deleting file '$_file'" && rm $_file
+[[ -f "$_file" ]] && log_debug "Deleting file '$_file'" && rm $_file
 _file=$BO_Project/src/lib/third_party/pytest.log
-[[ -f "$_file" ]] && echo "INFO: Deleting file '$_file'" && rm $_file
+[[ -f "$_file" ]] && log_debug "Deleting file '$_file'" && rm $_file
 
-echo "WARN: Found these files REMAINING..."
+log_warn "Found these files REMAINING..."
 findAnd print $BO_Project '*.bak'
 findAnd print $BO_Project '*.log'
 findAnd print $BO_Project '*.pyc'
 findAnd print $BO_Project '__pycache__'
 
 main() {
-    # TODO: DESCRIPTION
+    # Clean project directory
 
     # TODO: CONTENT
 
@@ -73,11 +64,9 @@ main $@
 
 ###############################################################################
 # NOTE: Uncomment these lines for debugging, placed where needed
-# set -o verbose
-# set -o xtrace
+# export PS4='$ ' ; set -o verbose ; set -o xtrace
 # Code to debug...
-# set +o verbose
-# set +o xtrace
+# set +o verbose ; set +o xtrace
 : << 'DisabledContent'
 DisabledContent
 
diff --git a/BriteOnyx/bin/prj-wipe b/BriteOnyx/bin/prj-wipe
--- a/BriteOnyx/bin/prj-wipe
+++ b/BriteOnyx/bin/prj-wipe
@@ -1,30 +1,21 @@
 #!/usr/bin/env bash
-[[ -n "${BO_Debug}" ]] && 1>&2 echo "DEBUG: Executing ${BASH_SOURCE}"
+[[ -n "${BO_Debug}" ]] && 1>&2 echo "Executing ${BASH_SOURCE}"
 # NO: set -e
 # Intended to be executed in a BASH shell.
-
-report_status_and_exit() {
-    local -ir Status=$?
-    [[ "${Status}" -ne 0 ]] && 
-        1>&2 echo "FATAL: ${0} exiting with status ${Status}"
-    exit ${Status}
-}
-trap report_status_and_exit EXIT
+trap warn_on_error EXIT
 ###############################################################################
-# Wipe project directory, which is a deeper clean
-
-[[ -z "${BO_Project}" ]] && 
-    1>&2 echo "FATAL: This project is NOT ACTIVATED, aborting" && 
+[[ -z "${BO_Project}" ]] &&
+    log_error "Aborting, this project is NOT ACTIVATED" &&
     exit 99
 
 if [[ -z "$PVE" ]] ; then
-    echo "FATAL: Environment variable 'PVE' is undefined, aborting"
+    log_error "Environment variable 'PVE' is undefined, aborting"
     exit 1
 fi
 
 prj-clean
 
-echo "INFO: Wiping (cleaning deeper)..."
+log_debug "Wiping (cleaning deeper)..."
 rm -fr $BO_Project/.pytest_cache 
 rm -fr $BO_Project/log 
 pve-rm
@@ -32,7 +23,7 @@ pve-rm
 # TODO: Wipe other caches such as for 'pip'
 
 main() {
-    # TODO: DESCRIPTION
+    # Wipe project directory, which is a deeper clean
 
     # TODO: CONTENT
 
@@ -43,11 +34,9 @@ main $@
 
 ###############################################################################
 # NOTE: Uncomment these lines for debugging, placed where needed
-# set -o verbose
-# set -o xtrace
+# export PS4='$ ' ; set -o verbose ; set -o xtrace
 # Code to debug...
-# set +o verbose
-# set +o xtrace
+# set +o verbose ; set +o xtrace
 : << 'DisabledContent'
 DisabledContent
 
diff --git a/BriteOnyx/bin/pve-rm b/BriteOnyx/bin/pve-rm
--- a/BriteOnyx/bin/pve-rm
+++ b/BriteOnyx/bin/pve-rm
@@ -1,32 +1,23 @@
 #!/usr/bin/env bash
-[[ -n "${BO_Debug}" ]] && 1>&2 echo "DEBUG: Executing ${BASH_SOURCE}"
+[[ -n "${BO_Debug}" ]] && 1>&2 echo "Executing ${BASH_SOURCE}"
 # NO: set -e
 # Intended to be executed in a BASH shell.
-
-report_status_and_exit() {
-    local -ir Status=$?
-    [[ "${Status}" -ne 0 ]] && 
-        1>&2 echo "FATAL: ${0} exiting with status ${Status}"
-    exit ${Status}
-}
-trap report_status_and_exit EXIT
+trap warn_on_error EXIT
 ###############################################################################
-# Remove Python virtual environment directory
-
-[[ -z "${BO_Project}" ]] && 
-    1>&2 echo "FATAL: This project is NOT ACTIVATED, aborting" && 
+[[ -z "${BO_Project}" ]] &&
+    log_error "Aborting, this project is NOT ACTIVATED" &&
     exit 99
 
 if [[ -z "$PVE" ]] ; then
-    echo "FATAL: Environment variable 'PVE' is undefined, aborting"
+    log_error "Environment variable 'PVE' is undefined, aborting"
     exit 1
 fi
 
-echo "INFO: Removing Python virtual environment directory '$PVE'"
+log_debug "Removing Python virtual environment directory '$PVE'"
 rm -fr $PVE
 
 main() {
-    # TODO: DESCRIPTION
+    # Remove Python virtual environment directory
 
     # TODO: CONTENT
 
@@ -37,11 +28,9 @@ main $@
 
 ###############################################################################
 # NOTE: Uncomment these lines for debugging, placed where needed
-# set -o verbose
-# set -o xtrace
+# export PS4='$ ' ; set -o verbose ; set -o xtrace
 # Code to debug...
-# set +o verbose
-# set +o xtrace
+# set +o verbose ; set +o xtrace
 : << 'DisabledContent'
 DisabledContent
 
diff --git a/BriteOnyx/bin/py-capture b/BriteOnyx/bin/py-capture
--- a/BriteOnyx/bin/py-capture
+++ b/BriteOnyx/bin/py-capture
@@ -1,29 +1,20 @@
 #!/usr/bin/env bash
-[[ -n "${BO_Debug}" ]] && 1>&2 echo "DEBUG: Executing ${BASH_SOURCE}"
+[[ -n "${BO_Debug}" ]] && 1>&2 echo "Executing ${BASH_SOURCE}"
 # NO: set -e
 # Intended to be executed in a BASH shell.
-
-report_status_and_exit() {
-    local -ir Status=$?
-    [[ "${Status}" -ne 0 ]] && 
-        1>&2 echo "FATAL: ${0} exiting with status ${Status}"
-    exit ${Status}
-}
-trap report_status_and_exit EXIT
+trap warn_on_error EXIT
 ###############################################################################
-# Capture Python status
-
-[[ -z "${BO_Project}" ]] && 
-    1>&2 echo "FATAL: This project is NOT ACTIVATED, aborting" && 
+[[ -z "${BO_Project}" ]] &&
+    log_error "Aborting, this project is NOT ACTIVATED" &&
     exit 99
 
 File=${BO_Project}/out/python.out
 
-echo "INFO:  Capturing Python status to '${File}'"
+log_debug "Capturing Python status to '${File}'"
 >${File} py-report
 
 main() {
-    # TODO: DESCRIPTION
+    # Capture Python status
 
     # TODO: CONTENT
 
@@ -34,11 +25,9 @@ main $@
 
 ###############################################################################
 # NOTE: Uncomment these lines for debugging, placed where needed
-# set -o verbose
-# set -o xtrace
+# export PS4='$ ' ; set -o verbose ; set -o xtrace
 # Code to debug...
-# set +o verbose
-# set +o xtrace
+# set +o verbose ; set +o xtrace
 : << 'DisabledContent'
 DisabledContent
 
diff --git a/BriteOnyx/bin/py-check b/BriteOnyx/bin/py-check
--- a/BriteOnyx/bin/py-check
+++ b/BriteOnyx/bin/py-check
@@ -1,34 +1,25 @@
 #!/usr/bin/env bash
-[[ -n "${BO_Debug}" ]] && 1>&2 echo "DEBUG: Executing ${BASH_SOURCE}"
+[[ -n "${BO_Debug}" ]] && 1>&2 echo "Executing ${BASH_SOURCE}"
 # NO: set -e
 # Intended to be executed in a BASH shell.
-
-report_status_and_exit() {
-    local -ir Status=$?
-    [[ "${Status}" -ne 0 ]] && 
-        1>&2 echo "FATAL: ${0} exiting with status ${Status}"
-    exit ${Status}
-}
-trap report_status_and_exit EXIT
+trap warn_on_error EXIT
 ###############################################################################
-# Check Python status
-
-[[ -z "${BO_Project}" ]] && 
-    1>&2 echo "FATAL: This project is NOT ACTIVATED, aborting" && 
+[[ -z "${BO_Project}" ]] &&
+    log_error "Aborting, this project is NOT ACTIVATED" &&
     exit 99
 
 File=$BO_Project/out/Python.out
 
 if [[ ! -r "$File" ]] ; then
-    echo "FATAL: Python status file '$File' is unreadable, aborting"
+    log_error "Python status file '$File' is unreadable, aborting"
     exit 1
 fi
 
-echo "INFO: Checking Python status against '$File'"
+log_debug "Checking Python status against '$File'"
 py-report | diff - $File
 
 main() {
-    # TODO: DESCRIPTION
+    # Check Python status
 
     # TODO: CONTENT
 
@@ -39,11 +30,9 @@ main $@
 
 ###############################################################################
 # NOTE: Uncomment these lines for debugging, placed where needed
-# set -o verbose
-# set -o xtrace
+# export PS4='$ ' ; set -o verbose ; set -o xtrace
 # Code to debug...
-# set +o verbose
-# set +o xtrace
+# set +o verbose ; set +o xtrace
 : << 'DisabledContent'
 DisabledContent
 
diff --git a/BriteOnyx/bin/py-compile b/BriteOnyx/bin/py-compile
--- a/BriteOnyx/bin/py-compile
+++ b/BriteOnyx/bin/py-compile
@@ -1,23 +1,14 @@
 #!/usr/bin/env bash
-[[ -n "${BO_Debug}" ]] && 1>&2 echo "DEBUG: Executing ${BASH_SOURCE}"
+[[ -n "${BO_Debug}" ]] && 1>&2 echo "Executing ${BASH_SOURCE}"
 # NO: set -e
 # Intended to be executed in a BASH shell.
-
-report_status_and_exit() {
-    local -ir Status=$?
-    [[ "${Status}" -ne 0 ]] && 
-        1>&2 echo "FATAL: ${0} exiting with status ${Status}"
-    exit ${Status}
-}
-trap report_status_and_exit EXIT
+trap warn_on_error EXIT
 ###############################################################################
-# Compile all Python source
-
-[[ -z "${BO_Project}" ]] && 
-    1>&2 echo "FATAL: This project is NOT ACTIVATED, aborting" && 
+[[ -z "${BO_Project}" ]] &&
+    log_error "Aborting, this project is NOT ACTIVATED" &&
     exit 99
 
-echo "INFO: Compiling Python source files..."
+log_debug "Compiling Python source files..."
 python3 -m compileall -f $BO_Project/BriteOnyx/bin
 python3 -m compileall -f $BO_Project/bin
 python3 -m compileall -f $BO_Project/src/app
@@ -25,7 +16,7 @@ python3 -m compileall -f $BO_Project/src/gen
 python3 -m compileall -f $BO_Project/src/lib
 
 main() {
-    # TODO: DESCRIPTION
+    # Compile all Python source
 
     # TODO: CONTENT
 
@@ -36,11 +27,9 @@ main $@
 
 ###############################################################################
 # NOTE: Uncomment these lines for debugging, placed where needed
-# set -o verbose
-# set -o xtrace
+# export PS4='$ ' ; set -o verbose ; set -o xtrace
 # Code to debug...
-# set +o verbose
-# set +o xtrace
+# set +o verbose ; set +o xtrace
 : << 'DisabledContent'
 DisabledContent
 
diff --git a/BriteOnyx/bin/py-reformat b/BriteOnyx/bin/py-reformat
--- a/BriteOnyx/bin/py-reformat
+++ b/BriteOnyx/bin/py-reformat
@@ -1,30 +1,21 @@
 #!/usr/bin/env bash
-[[ -n "${BO_Debug}" ]] && 1>&2 echo "DEBUG: Executing ${BASH_SOURCE}"
+[[ -n "${BO_Debug}" ]] && 1>&2 echo "Executing ${BASH_SOURCE}"
 # NO: set -e
 # Intended to be executed in a BASH shell.
-
-report_status_and_exit() {
-    local -ir Status=$?
-    [[ "${Status}" -ne 0 ]] && 
-        1>&2 echo "FATAL: ${0} exiting with status ${Status}"
-    exit ${Status}
-}
-trap report_status_and_exit EXIT
+trap warn_on_error EXIT
 ###############################################################################
-# Reformat Python code using Black
-
-[[ -z "${BO_Project}" ]] && 
-    1>&2 echo "FATAL: This project is NOT ACTIVATED, aborting" && 
+[[ -z "${BO_Project}" ]] &&
+    log_error "Aborting, this project is NOT ACTIVATED" &&
     exit 99
 
 # Temporarily override user setting to keep Black's cache under BO_Project
 export XDG_CACHE_HOME=${BO_Project}/.cache
 
-echo "INFO: Reformatting Python code using Black"
+log_debug "Reformatting Python code using Black"
 black --config ${BO_Project}/cfg/pyproject.toml ${BO_Project}
 
 main() {
-    # TODO: DESCRIPTION
+    # Reformat Python code using Black
 
     # TODO: CONTENT
 
@@ -35,11 +26,9 @@ main $@
 
 ###############################################################################
 # NOTE: Uncomment these lines for debugging, placed where needed
-# set -o verbose
-# set -o xtrace
+# export PS4='$ ' ; set -o verbose ; set -o xtrace
 # Code to debug...
-# set +o verbose
-# set +o xtrace
+# set +o verbose ; set +o xtrace
 : << 'DisabledContent'
 DisabledContent
 
diff --git a/BriteOnyx/bin/py-report b/BriteOnyx/bin/py-report
--- a/BriteOnyx/bin/py-report
+++ b/BriteOnyx/bin/py-report
@@ -1,23 +1,12 @@
 #!/usr/bin/env bash
-[[ -n "${BO_Debug}" ]] && 1>&2 echo "DEBUG: Executing ${BASH_SOURCE}"
+[[ -n "${BO_Debug}" ]] && 1>&2 echo "Executing ${BASH_SOURCE}"
 # NO: set -e
 # Intended to be executed in a BASH shell.
-
-report_status_and_exit() {
-    local -ir Status=$?
-    [[ "${Status}" -ne 0 ]] && 
-        1>&2 echo "FATAL: ${0} exiting with status ${Status}"
-    exit ${Status}
-}
-trap report_status_and_exit EXIT
+trap warn_on_error EXIT
 ###############################################################################
-# Report Python code status
-
-[[ -z "${BO_Project}" ]] && 
-    1>&2 echo "FATAL: This project is NOT ACTIVATED, aborting" && 
+[[ -z "${BO_Project}" ]] &&
+    log_error "Aborting, this project is NOT ACTIVATED" &&
     exit 99
-
-clear
 
 Out=${BO_Project}/out/tabnanny.out
  >${Out} 2>&1 python3 -m tabnanny -v ${BO_Project}/BriteOnyx/bin
@@ -28,13 +17,13 @@ Out=${BO_Project}/out/tabnanny.out
 cat ${Out} \
     | grep -v 'listing directory' \
     | grep -v 'Clean bill of health.'
-echo 'INFO: No output means all Python code passes all TabNanny checks'
+log_debug "No output means all Python code passes all TabNanny checks"
 
 Out=${BO_Project}/out/py-reformat.out
->${Out} 2>&1 py-reformat
+&>${Out} py-reformat
 
 main() {
-    # TODO: DESCRIPTION
+    # Report Python code status
 
     # TODO: CONTENT
 
@@ -45,11 +34,9 @@ main $@
 
 ###############################################################################
 # NOTE: Uncomment these lines for debugging, placed where needed
-# set -o verbose
-# set -o xtrace
+# export PS4='$ ' ; set -o verbose ; set -o xtrace
 # Code to debug...
-# set +o verbose
-# set +o xtrace
+# set +o verbose ; set +o xtrace
 : << 'DisabledContent'
 DisabledContent
 
diff --git a/BriteOnyx/bin/sig-make b/BriteOnyx/bin/sig-make
--- a/BriteOnyx/bin/sig-make
+++ b/BriteOnyx/bin/sig-make
@@ -1,31 +1,22 @@
 #!/usr/bin/env bash
-[[ -n "${BO_Debug}" ]] && 1>&2 echo "DEBUG: Executing ${BASH_SOURCE}"
+[[ -n "${BO_Debug}" ]] && 1>&2 echo "Executing ${BASH_SOURCE}"
 # NO: set -e
 # Intended to be executed in a BASH shell.
-
-report_status_and_exit() {
-    local -ir Status=$?
-    [[ "${Status}" -ne 0 ]] && 
-        1>&2 echo "FATAL: ${0} exiting with status ${Status}"
-    exit ${Status}
-}
-trap report_status_and_exit EXIT
+trap warn_on_error EXIT
 ###############################################################################
-# Make a signature file for directory $1
-
-[[ -z "${BO_Project}" ]] && 
-    1>&2 echo "FATAL: This project is NOT ACTIVATED, aborting" && 
+[[ -z "${BO_Project}" ]] &&
+    log_error "Aborting, this project is NOT ACTIVATED" &&
     exit 99
 
 file=shasum-256.sig
 
-echo "INFO:  Making signature file ${dir}/${file}"
+log_debug "Making signature file ${dir}/${file}"
 cd ${dir}
 shasum -p -a 256 * 2>/dev/null | grep -v ${file} >${file}
 cat ${file}
 
 main() {
-    # TODO: DESCRIPTION
+    # Make signature file for directory $1
 
     # TODO: CONTENT
 
@@ -36,11 +27,9 @@ main $@
 
 ###############################################################################
 # NOTE: Uncomment these lines for debugging, placed where needed
-# set -o verbose
-# set -o xtrace
+# export PS4='$ ' ; set -o verbose ; set -o xtrace
 # Code to debug...
-# set +o verbose
-# set +o xtrace
+# set +o verbose ; set +o xtrace
 : << 'DisabledContent'
 DisabledContent
 
diff --git a/bin/tool-report b/bin/tool-report
--- a/bin/tool-report
+++ b/bin/tool-report
@@ -1,20 +1,11 @@
 #!/usr/bin/env bash
-[[ -n "${BO_Debug}" ]] && 1>&2 echo "DEBUG: Executing ${BASH_SOURCE}"
+[[ -n "${BO_Debug}" ]] && 1>&2 echo "Executing ${BASH_SOURCE}"
 # NO: set -e
 # Intended to be executed in a BASH shell.
-
-report_status_and_exit() {
-    local -ir Status=$?
-    [[ "${Status}" -ne 0 ]] && 
-        1>&2 echo "FATAL: ${0} exiting with status ${Status}"
-    exit ${Status}
-}
-trap report_status_and_exit EXIT
+trap warn_on_error EXIT
 ###############################################################################
-# Report tool status
-
-[[ -z "${BO_Project}" ]] && 
-    1>&2 echo "FATAL: This project is NOT ACTIVATED, aborting" && 
+[[ -z "${BO_Project}" ]] &&
+    log_error "Aborting, this project is NOT ACTIVATED" &&
     exit 99
 
 Rule=##########
@@ -56,7 +47,7 @@ check 'compgen -b'
 check 'compgen -c'
 check 'compgen -e'
 # TODO: RESEARCH:  Why is this call so time-consuming on some machines?
-check 'compgen -g'
+# check 'compgen -g'
 check 'compgen -k'
 
 # Git
@@ -76,7 +67,7 @@ checkVariable PYTHONPATH "$PYTHONPATH"
 
 # Python 2
 checkExecutable python2
-check 'python2 --version' 2>&1
+2>&1 check 'python2 --version'
 echo $Rule
 python2 -c 'import platform; print(platform.python_version())'
 echo $Rule
@@ -102,10 +93,10 @@ checkExecutable coverage
 check 'coverage --version'
 checkExecutable py.test
 checkExecutable pytest
-check 'pytest --version' 2>&1
+2>&1 check 'pytest --version'
 
 main() {
-    # TODO: DESCRIPTION
+    # Report tool status
 
     # TODO: CONTENT
 
@@ -116,11 +107,9 @@ main $@
 
 ###############################################################################
 # NOTE: Uncomment these lines for debugging, placed where needed
-# set -o verbose
-# set -o xtrace
+# export PS4='$ ' ; set -o verbose ; set -o xtrace
 # Code to debug...
-# set +o verbose
-# set +o xtrace
+# set +o verbose ; set +o xtrace
 : << 'DisabledContent'
 # AWS CLI
 checkExecutable aws
