Prepare to use Anaconda environment

diff --git a/BriteOnyx/bin/prj-clean b/BriteOnyx/bin/prj-clean
--- a/BriteOnyx/bin/prj-clean
+++ b/BriteOnyx/bin/prj-clean
@@ -8,11 +8,6 @@ trap warn_on_error EXIT
     1>&2 echo "ERROR: Aborting, this project is NOT ACTIVATED" &&
     exit 99
 
-if [[ -z "${BO_PVE}" ]] ; then
-    log_error "Environment variable 'BO_PVE' is undefined, aborting"
-    exit 1
-fi
-
 findAnd() {
     # Find and perform action $1 on files within directory $2 matching pattern $3
     # $1 = action to perform, either 'delete' or 'print'
@@ -20,7 +15,6 @@ findAnd() {
     # $3 = filename pattern to match
     find "$2" \
 	-not -path "${BO_Project}/.git/*" \
-	-and -not -path "${BO_PVE}/*" \
 	-and -name "$3" \
 	-and -type f \
 	-$1
@@ -64,5 +58,11 @@ main $@
 # set +vx
 
 : << 'DisabledContent'
+if [[ -z "${BO_PVE}" ]] ; then
+    log_error "Environment variable 'BO_PVE' is undefined, aborting"
+    exit 1
+fi
+
+	-and -not -path "${BO_PVE}/*" \
 DisabledContent
 
diff --git a/BriteOnyx/bin/prj-wipe b/BriteOnyx/bin/prj-wipe
--- a/BriteOnyx/bin/prj-wipe
+++ b/BriteOnyx/bin/prj-wipe
@@ -8,11 +8,6 @@ trap warn_on_error EXIT
     1>&2 echo "ERROR: Aborting, this project is NOT ACTIVATED" &&
     exit 99
 
-if [[ -z "${BO_PVE}" ]] ; then
-    log_error "Environment variable 'BO_PVE' is undefined, aborting"
-    exit 1
-fi
-
 main() {
     # Wipe project directory, which is a deeper clean
     # TODO: Wipe other caches such as for 'pip'
@@ -22,7 +17,7 @@ main() {
     log_debug "Wiping (cleaning deeper)..."
     maybe_delete_directory_tree "${BO_Project}/.pytest_cache"
     maybe_delete_directory_tree "${BO_Project}/log"
-    pve-rm
+#   pve-rm
 
     return 0
 }
@@ -36,5 +31,10 @@ main $@
 # set +vx
 
 : << 'DisabledContent'
+if [[ -z "${BO_PVE}" ]] ; then
+    log_error "Environment variable 'BO_PVE' is undefined, aborting"
+    exit 1
+fi
+
 DisabledContent
 
