Fix handling of Python virtual environment ; Sync with another project ; Update generated sources

diff --git a/BriteOnyx/bin/pve-create b/BriteOnyx/bin/pve-create
--- a/BriteOnyx/bin/pve-create
+++ b/BriteOnyx/bin/pve-create
@@ -5,16 +5,16 @@
 trap warn_on_error EXIT
 ###############################################################################
 [[ -z "${BO_Project}" ]] &&
-    log_error "Aborting, this project is NOT ACTIVATED" &&
+    1>&2 echo "ERROR: Aborting, this project is NOT ACTIVATED" &&
     exit 99
 
-if [[ -z "$PVE" ]] ; then
-    log_error "Environment variable 'PVE' is undefined, aborting"
+if [[ -z "$BO_PVE" ]] ; then
+    log_error "Environment variable 'BO_PVE' is undefined, aborting"
     exit 1
 fi
 
-log_debug "Creating Python virtual environment directory '$PVE'"
-python3 -m venv $PVE
+log_debug "Creating Python virtual environment directory '$BO_PVE'"
+python3 -m venv $BO_PVE
 
 echo 'WARN: This new Python virtual environment has NOT been activated, so you should `exit` this shell and activate a new one'
 
diff --git a/BriteOnyx/bin/pve-reinstall b/BriteOnyx/bin/pve-reinstall
--- a/BriteOnyx/bin/pve-reinstall
+++ b/BriteOnyx/bin/pve-reinstall
@@ -5,15 +5,15 @@
 trap warn_on_error EXIT
 ###############################################################################
 [[ -z "${BO_Project}" ]] &&
-    log_error "Aborting, this project is NOT ACTIVATED" &&
+    1>&2 echo "ERROR: Aborting, this project is NOT ACTIVATED" &&
     exit 99
 
-if [[ -z "$PVE" ]] ; then
-    log_error "Environment variable 'PVE' is undefined, aborting"
+if [[ -z "$BO_PVE" ]] ; then
+    log_error "Environment variable 'BO_PVE' is undefined, aborting"
     exit 1
 fi
 
-log_debug "Reinstalling Python virtual environment directory '$PVE'"
+log_debug "Reinstalling Python virtual environment directory '$BO_PVE'"
 pve-rm
 pve-create
 source $BO_Project/BriteOnyx/bin/lib/pve-activate.bash
