Improve status management

diff --git a/BriteOnyx/bin/py-check b/BriteOnyx/bin/py-check
--- a/BriteOnyx/bin/py-check
+++ b/BriteOnyx/bin/py-check
@@ -2,24 +2,20 @@
 # This script is intended to be executed by a user in a BASH shell.
 set -e
 
-# Check Python code
+# Check Python status
 
 if [[ -z "$BO_Project" ]] ; then
     echo "FATAL: Environment variable 'BO_Project' is undefined, aborting"
     exit 1
 fi
 
-clear
+File=$BO_Project/out/Python.out
 
-python3 -m tabnanny -v $BO_Project/BriteOnyx/bin >$BO_Project/out/tabnanny.out
-python3 -m tabnanny -v $BO_Project/bin          >>$BO_Project/out/tabnanny.out
-python3 -m tabnanny -v $BO_Project/gen          >>$BO_Project/out/tabnanny.out
-python3 -m tabnanny -v $BO_Project/lib          >>$BO_Project/out/tabnanny.out
-python3 -m tabnanny -v $BO_Project/src          >>$BO_Project/out/tabnanny.out
+if [[ ! -r "$File" ]] ; then
+    echo "FATAL: Python status file '$File' is unreadable, aborting"
+    exit 1
+fi
 
-cat $BO_Project/out/tabnanny.out \
-    | grep -v 'listing directory' \
-    | grep -v 'Clean bill of health.'
-
-echo 'INFO: No output means all Python code passes all checks'
+echo "INFO: Checking Python status against '$File'"
+py-report | diff - $File
 
